USE BolBcp

--PASO 1 SEPARA LOS VALORES POR TIPO CLASIFICACION
DROP TABLE IF EXISTS ##TEMP1
SELECT CAST(FECHA AS DATE) AS FECHA
	  ,tc.CODIGO_ENTIDAD
	  ,e.Entidad
	  --,CLASIFICACIÓN
	  ,CASE WHEN CLASIFICACIÓN='Cantidad' THEN TOTAL ELSE 0 END AS CantTC
	  ,CASE WHEN CLASIFICACIÓN='Saldo' THEN TOTAL ELSE 0 END AS SaldoTC
	  ,TOTAL
	  ,FECHA_CARGA
 INTO ##TEMP1	-- SELECT * FROM ##TEMP1
 FROM dbo.TC JOIN dbo.DeParabanco e ON tc.codigo_entidad=e.Codigo_Entidad

 -- PASO 2 AGRUPAR POR TOTALES DE TIPO CLASIFICACION EN UNA SOLA LINEA POR FECHA CIERRE Y ENTIDAD
SELECT FECHA
	  ,CODIGO_ENTIDAD
	  ,Entidad
	  --,CLASIFICACIÓN
	  ,SUM(CantTC) AS CantTC
	  ,SUM(SaldoTC) AS SaldoTC
	  ,SUM(TOTAL) AS TOTAL
  FROM ##TEMP1
  GROUP BY FECHA,CODIGO_ENTIDAD,Entidad
